# Generated by Django 3.2.4 on 2022-06-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
